task:
    id: "040"
    name: Create Prompt Functions
    phase: implementation
    status: completed
    created_at: 2025-11-03T15:09:53.36376-08:00
    started_at: 2025-11-03T15:32:14.579185-08:00
    updated_at: 2025-11-03T15:32:14.579184-08:00
    completed_at: 2025-11-03T15:32:14.579185-08:00
    iteration: 1
    assigned_agent: implementer
    references: []
    feedback: []
    files_modified:
        - cli/internal/projects/standard/prompts.go
