task:
    id: "020"
    name: Builder API Implementation
    phase: implementation
    status: completed
    created_at: 2025-11-03T12:50:22.733395-08:00
    started_at: 2025-11-03T12:58:52.454941-08:00
    updated_at: 2025-11-03T13:02:20.745415-08:00
    completed_at: 2025-11-03T13:02:20.745415-08:00
    iteration: 1
    assigned_agent: implementer
    references: []
    feedback: []
    files_modified:
        - cli/internal/sdks/project/builder_test.go
        - cli/internal/sdks/project/builder.go
